site_name: Tech Community Talk - Material for MkDocs
theme:
  name: material
  features:
    - content.code.copy
#  features:
#    # tabs
#    - navigation.tabs
#    # sticky behaviour
#    - navigation.tabs.sticky
#    - toc.integrate
#    - toc.follow
#
#  palette:
#  # Palette toggle for light mode
#  - scheme: default
#    toggle:
#      icon: material/brightness-7
#      name: Switch to dark mode
#  # Palette toggle for dark mode
#  - scheme: slate
#    toggle:
#      icon: material/brightness-4
#      name: Switch to light mode
#
#nav:
#  - Home: config.md
#  - Getting started:
#    - installation/setup.md
#  - Customization:
#    - customization/config.md
#    - customization/features.md
#  - Publishing:
#    - publishing/github_pages.md
#  - Example Project:
#    - example_project/observability_docs.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
